name: Automate Steps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
          pip install pytest
          pip install pylint

      - name: Model Training
        run: python bikeshare_model/train_pipeline.py

      - name: Run Tests
        run: python -m pytest bikeshare_model/test_features.py bikeshare_model/test_prediction.py

      - name: Linting
        run: pylint bikeshare_model

      - name: Formatting
        run: black bikeshare_model

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automated workflow changes"
          commit_options: '--no-verify'
